language: objective-c
osx_image: xcode7.1

before_install:
  - brew update && brew tap nviennot/tmate && brew install tmate
  - tmate -S /tmp/tmate.sock new-session -d
  - tmate -S /tmp/tmate.sock wait tmate-ready
  - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'

script:
  - sleep 6000

