language: objective-c

matrix:
  include:
    - osx_image: xcode7.1
    - osx_image: xcode7
    - osx_image: osx10.11

script:
  - uname -a
  - fastlane --version
  - motion --version
  - pod --version
  - xctool --version
  - xcpretty --version

